// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SEP.proto

package com.sep.protobuf;

public interface CreateProjectDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateProjectDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 userId = 1;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>string projectName = 2;</code>
   * @return The projectName.
   */
  java.lang.String getProjectName();
  /**
   * <code>string projectName = 2;</code>
   * @return The bytes for projectName.
   */
  com.google.protobuf.ByteString
      getProjectNameBytes();
}
