// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SEP.proto

package com.sep.protobuf;

public interface LoginUserDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LoginUserDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string UserName = 1;</code>
   * @return The userName.
   */
  java.lang.String getUserName();
  /**
   * <code>string UserName = 1;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string Password = 2;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string Password = 2;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
