// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SEP.proto

package com.sep.protobuf;

/**
 * Protobuf type {@code Project}
 */
public final class Project extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Project)
    ProjectOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Project.newBuilder() to construct.
  private Project(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Project() {
    projectName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Project();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Project(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            projectName_ = s;
            break;
          }
          case 26: {
            com.sep.protobuf.User.Builder subBuilder = null;
            if (owner_ != null) {
              subBuilder = owner_.toBuilder();
            }
            owner_ = input.readMessage(com.sep.protobuf.User.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(owner_);
              owner_ = subBuilder.buildPartial();
            }

            break;
          }
          case 32: {

            isCompleted_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sep.protobuf.SEP.internal_static_Project_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sep.protobuf.SEP.internal_static_Project_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sep.protobuf.Project.class, com.sep.protobuf.Project.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int PROJECTNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object projectName_;
  /**
   * <code>string projectName = 2;</code>
   * @return The projectName.
   */
  @java.lang.Override
  public java.lang.String getProjectName() {
    java.lang.Object ref = projectName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      projectName_ = s;
      return s;
    }
  }
  /**
   * <code>string projectName = 2;</code>
   * @return The bytes for projectName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProjectNameBytes() {
    java.lang.Object ref = projectName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      projectName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OWNER_FIELD_NUMBER = 3;
  private com.sep.protobuf.User owner_;
  /**
   * <code>.User owner = 3;</code>
   * @return Whether the owner field is set.
   */
  @java.lang.Override
  public boolean hasOwner() {
    return owner_ != null;
  }
  /**
   * <code>.User owner = 3;</code>
   * @return The owner.
   */
  @java.lang.Override
  public com.sep.protobuf.User getOwner() {
    return owner_ == null ? com.sep.protobuf.User.getDefaultInstance() : owner_;
  }
  /**
   * <code>.User owner = 3;</code>
   */
  @java.lang.Override
  public com.sep.protobuf.UserOrBuilder getOwnerOrBuilder() {
    return getOwner();
  }

  public static final int ISCOMPLETED_FIELD_NUMBER = 4;
  private boolean isCompleted_;
  /**
   * <code>bool isCompleted = 4;</code>
   * @return The isCompleted.
   */
  @java.lang.Override
  public boolean getIsCompleted() {
    return isCompleted_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(projectName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, projectName_);
    }
    if (owner_ != null) {
      output.writeMessage(3, getOwner());
    }
    if (isCompleted_ != false) {
      output.writeBool(4, isCompleted_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(projectName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, projectName_);
    }
    if (owner_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getOwner());
    }
    if (isCompleted_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, isCompleted_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sep.protobuf.Project)) {
      return super.equals(obj);
    }
    com.sep.protobuf.Project other = (com.sep.protobuf.Project) obj;

    if (getId()
        != other.getId()) return false;
    if (!getProjectName()
        .equals(other.getProjectName())) return false;
    if (hasOwner() != other.hasOwner()) return false;
    if (hasOwner()) {
      if (!getOwner()
          .equals(other.getOwner())) return false;
    }
    if (getIsCompleted()
        != other.getIsCompleted()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + PROJECTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getProjectName().hashCode();
    if (hasOwner()) {
      hash = (37 * hash) + OWNER_FIELD_NUMBER;
      hash = (53 * hash) + getOwner().hashCode();
    }
    hash = (37 * hash) + ISCOMPLETED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsCompleted());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sep.protobuf.Project parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sep.protobuf.Project parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sep.protobuf.Project parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sep.protobuf.Project parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sep.protobuf.Project parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sep.protobuf.Project parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sep.protobuf.Project parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sep.protobuf.Project parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sep.protobuf.Project parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.sep.protobuf.Project parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sep.protobuf.Project parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sep.protobuf.Project parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sep.protobuf.Project prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Project}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Project)
      com.sep.protobuf.ProjectOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sep.protobuf.SEP.internal_static_Project_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sep.protobuf.SEP.internal_static_Project_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sep.protobuf.Project.class, com.sep.protobuf.Project.Builder.class);
    }

    // Construct using com.sep.protobuf.Project.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      projectName_ = "";

      if (ownerBuilder_ == null) {
        owner_ = null;
      } else {
        owner_ = null;
        ownerBuilder_ = null;
      }
      isCompleted_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sep.protobuf.SEP.internal_static_Project_descriptor;
    }

    @java.lang.Override
    public com.sep.protobuf.Project getDefaultInstanceForType() {
      return com.sep.protobuf.Project.getDefaultInstance();
    }

    @java.lang.Override
    public com.sep.protobuf.Project build() {
      com.sep.protobuf.Project result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sep.protobuf.Project buildPartial() {
      com.sep.protobuf.Project result = new com.sep.protobuf.Project(this);
      result.id_ = id_;
      result.projectName_ = projectName_;
      if (ownerBuilder_ == null) {
        result.owner_ = owner_;
      } else {
        result.owner_ = ownerBuilder_.build();
      }
      result.isCompleted_ = isCompleted_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sep.protobuf.Project) {
        return mergeFrom((com.sep.protobuf.Project)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sep.protobuf.Project other) {
      if (other == com.sep.protobuf.Project.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getProjectName().isEmpty()) {
        projectName_ = other.projectName_;
        onChanged();
      }
      if (other.hasOwner()) {
        mergeOwner(other.getOwner());
      }
      if (other.getIsCompleted() != false) {
        setIsCompleted(other.getIsCompleted());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.sep.protobuf.Project parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.sep.protobuf.Project) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object projectName_ = "";
    /**
     * <code>string projectName = 2;</code>
     * @return The projectName.
     */
    public java.lang.String getProjectName() {
      java.lang.Object ref = projectName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        projectName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string projectName = 2;</code>
     * @return The bytes for projectName.
     */
    public com.google.protobuf.ByteString
        getProjectNameBytes() {
      java.lang.Object ref = projectName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        projectName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string projectName = 2;</code>
     * @param value The projectName to set.
     * @return This builder for chaining.
     */
    public Builder setProjectName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      projectName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string projectName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearProjectName() {
      
      projectName_ = getDefaultInstance().getProjectName();
      onChanged();
      return this;
    }
    /**
     * <code>string projectName = 2;</code>
     * @param value The bytes for projectName to set.
     * @return This builder for chaining.
     */
    public Builder setProjectNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      projectName_ = value;
      onChanged();
      return this;
    }

    private com.sep.protobuf.User owner_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sep.protobuf.User, com.sep.protobuf.User.Builder, com.sep.protobuf.UserOrBuilder> ownerBuilder_;
    /**
     * <code>.User owner = 3;</code>
     * @return Whether the owner field is set.
     */
    public boolean hasOwner() {
      return ownerBuilder_ != null || owner_ != null;
    }
    /**
     * <code>.User owner = 3;</code>
     * @return The owner.
     */
    public com.sep.protobuf.User getOwner() {
      if (ownerBuilder_ == null) {
        return owner_ == null ? com.sep.protobuf.User.getDefaultInstance() : owner_;
      } else {
        return ownerBuilder_.getMessage();
      }
    }
    /**
     * <code>.User owner = 3;</code>
     */
    public Builder setOwner(com.sep.protobuf.User value) {
      if (ownerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        owner_ = value;
        onChanged();
      } else {
        ownerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.User owner = 3;</code>
     */
    public Builder setOwner(
        com.sep.protobuf.User.Builder builderForValue) {
      if (ownerBuilder_ == null) {
        owner_ = builderForValue.build();
        onChanged();
      } else {
        ownerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.User owner = 3;</code>
     */
    public Builder mergeOwner(com.sep.protobuf.User value) {
      if (ownerBuilder_ == null) {
        if (owner_ != null) {
          owner_ =
            com.sep.protobuf.User.newBuilder(owner_).mergeFrom(value).buildPartial();
        } else {
          owner_ = value;
        }
        onChanged();
      } else {
        ownerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.User owner = 3;</code>
     */
    public Builder clearOwner() {
      if (ownerBuilder_ == null) {
        owner_ = null;
        onChanged();
      } else {
        owner_ = null;
        ownerBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.User owner = 3;</code>
     */
    public com.sep.protobuf.User.Builder getOwnerBuilder() {
      
      onChanged();
      return getOwnerFieldBuilder().getBuilder();
    }
    /**
     * <code>.User owner = 3;</code>
     */
    public com.sep.protobuf.UserOrBuilder getOwnerOrBuilder() {
      if (ownerBuilder_ != null) {
        return ownerBuilder_.getMessageOrBuilder();
      } else {
        return owner_ == null ?
            com.sep.protobuf.User.getDefaultInstance() : owner_;
      }
    }
    /**
     * <code>.User owner = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sep.protobuf.User, com.sep.protobuf.User.Builder, com.sep.protobuf.UserOrBuilder> 
        getOwnerFieldBuilder() {
      if (ownerBuilder_ == null) {
        ownerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.sep.protobuf.User, com.sep.protobuf.User.Builder, com.sep.protobuf.UserOrBuilder>(
                getOwner(),
                getParentForChildren(),
                isClean());
        owner_ = null;
      }
      return ownerBuilder_;
    }

    private boolean isCompleted_ ;
    /**
     * <code>bool isCompleted = 4;</code>
     * @return The isCompleted.
     */
    @java.lang.Override
    public boolean getIsCompleted() {
      return isCompleted_;
    }
    /**
     * <code>bool isCompleted = 4;</code>
     * @param value The isCompleted to set.
     * @return This builder for chaining.
     */
    public Builder setIsCompleted(boolean value) {
      
      isCompleted_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool isCompleted = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsCompleted() {
      
      isCompleted_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Project)
  }

  // @@protoc_insertion_point(class_scope:Project)
  private static final com.sep.protobuf.Project DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sep.protobuf.Project();
  }

  public static com.sep.protobuf.Project getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Project>
      PARSER = new com.google.protobuf.AbstractParser<Project>() {
    @java.lang.Override
    public Project parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Project(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Project> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Project> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sep.protobuf.Project getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

