// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SEP.proto

package com.sep.protobuf;

public interface SearchTaskDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchTaskDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 userId = 1;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>string userName = 2;</code>
   * @return The userName.
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 2;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>int64 projectId = 3;</code>
   * @return The projectId.
   */
  long getProjectId();

  /**
   * <code>string projectName = 4;</code>
   * @return The projectName.
   */
  java.lang.String getProjectName();
  /**
   * <code>string projectName = 4;</code>
   * @return The bytes for projectName.
   */
  com.google.protobuf.ByteString
      getProjectNameBytes();

  /**
   * <code>string title = 5;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 5;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>bool isCompleted = 6;</code>
   * @return The isCompleted.
   */
  boolean getIsCompleted();
}
