// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SEP.proto

package com.sep.protobuf;

public interface SearchProjectDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchProjectDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 Userid = 1;</code>
   * @return The userid.
   */
  long getUserid();

  /**
   * <code>string userName = 2;</code>
   * @return The userName.
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 2;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>bool completedStatus = 3;</code>
   * @return The completedStatus.
   */
  boolean getCompletedStatus();

  /**
   * <code>string projectName = 4;</code>
   * @return The projectName.
   */
  java.lang.String getProjectName();
  /**
   * <code>string projectName = 4;</code>
   * @return The bytes for projectName.
   */
  com.google.protobuf.ByteString
      getProjectNameBytes();
}
