// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SEP.proto

package com.sep.protobuf;

public final class SEP {
  private SEP() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Project_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Project_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Task_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Task_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginUserDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginUserDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateUserDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateUserDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchUserDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchUserDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateProjectDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateProjectDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchProjectDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchProjectDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateProjectDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateProjectDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateTaskDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateTaskDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateTaskDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateTaskDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchTaskDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchTaskDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tSEP.proto\"U\n\007Project\022\n\n\002id\030\001 \001(\003\022\023\n\013pr" +
      "ojectName\030\002 \001(\t\022\024\n\005owner\030\003 \001(\0132\005.User\022\023\n" +
      "\013isCompleted\030\004 \001(\010\"n\n\004User\022\n\n\002id\030\001 \001(\003\022\020" +
      "\n\010UserName\030\002 \001(\t\022\020\n\010Password\030\003 \001(\t\022\027\n\010ta" +
      "skList\030\004 \003(\0132\005.Task\022\035\n\013projectList\030\005 \003(\013" +
      "2\010.Project\"i\n\004Task\022\n\n\002id\030\001 \001(\003\022\033\n\tbelong" +
      "sTo\030\002 \001(\0132\010.Project\022\r\n\005title\030\003 \001(\t\022\024\n\005ow" +
      "ner\030\004 \001(\0132\005.User\022\023\n\013isCompleted\030\005 \001(\010\"2\n" +
      "\014LoginUserDTO\022\020\n\010UserName\030\001 \001(\t\022\020\n\010Passw" +
      "ord\030\002 \001(\t\"3\n\rCreateUserDTO\022\020\n\010UserName\030\001" +
      " \001(\t\022\020\n\010Password\030\002 \001(\t\"-\n\rSearchUserDTO\022" +
      "\n\n\002id\030\001 \001(\003\022\020\n\010UserName\030\002 \001(\t\"7\n\020CreateP" +
      "rojectDTO\022\016\n\006userId\030\001 \001(\003\022\023\n\013projectName" +
      "\030\002 \001(\t\"b\n\020SearchProjectDTO\022\016\n\006Userid\030\001 \001" +
      "(\003\022\020\n\010userName\030\002 \001(\t\022\027\n\017completedStatus\030" +
      "\003 \001(\010\022\023\n\013projectName\030\004 \001(\t\"\036\n\020UpdateProj" +
      "ectDTO\022\n\n\002id\030\001 \001(\003\"B\n\rCreateTaskDTO\022\021\n\tp" +
      "rojectId\030\001 \001(\003\022\017\n\007ownerId\030\002 \001(\003\022\r\n\005title" +
      "\030\003 \001(\t\"0\n\rUpdateTaskDTO\022\n\n\002id\030\001 \001(\003\022\023\n\013i" +
      "sCompleted\030\002 \001(\010\"}\n\rSearchTaskDTO\022\016\n\006use" +
      "rId\030\001 \001(\003\022\020\n\010userName\030\002 \001(\t\022\021\n\tprojectId" +
      "\030\003 \001(\003\022\023\n\013projectName\030\004 \001(\t\022\r\n\005title\030\005 \001" +
      "(\t\022\023\n\013isCompleted\030\006 \001(\0102\301\001\n\013UserService\022" +
      "\035\n\005login\022\r.LoginUserDTO\032\005.User\022#\n\ncreate" +
      "User\022\016.CreateUserDTO\032\005.User\022#\n\010getUsers\022" +
      "\016.SearchUserDTO\032\005.User0\001\022$\n\013getUserById\022" +
      "\016.SearchUserDTO\032\005.User\022#\n\ndeleteUser\022\016.S" +
      "earchUserDTO\032\005.User2\310\001\n\016ProjectService\022," +
      "\n\rcreateProject\022\021.CreateProjectDTO\032\010.Pro" +
      "ject\022,\n\013getProjects\022\021.SearchProjectDTO\032\010" +
      ".Project0\001\022,\n\rupdateProject\022\021.UpdateProj" +
      "ectDTO\032\010.Project\022,\n\rdeleteProject\022\021.Sear" +
      "chProjectDTO\032\010.Project2\243\001\n\013TaskService\022#" +
      "\n\ncreateTask\022\016.CreateTaskDTO\032\005.Task\022#\n\010g" +
      "etTasks\022\016.SearchTaskDTO\032\005.Task0\001\022$\n\013upda" +
      "teTasks\022\016.UpdateTaskDTO\032\005.Task\022$\n\013delete" +
      "Tasks\022\016.SearchTaskDTO\032\005.TaskB\024\n\020com.sep." +
      "protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Project_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Project_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Project_descriptor,
        new java.lang.String[] { "Id", "ProjectName", "Owner", "IsCompleted", });
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_descriptor,
        new java.lang.String[] { "Id", "UserName", "Password", "TaskList", "ProjectList", });
    internal_static_Task_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Task_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Task_descriptor,
        new java.lang.String[] { "Id", "BelongsTo", "Title", "Owner", "IsCompleted", });
    internal_static_LoginUserDTO_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_LoginUserDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginUserDTO_descriptor,
        new java.lang.String[] { "UserName", "Password", });
    internal_static_CreateUserDTO_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_CreateUserDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateUserDTO_descriptor,
        new java.lang.String[] { "UserName", "Password", });
    internal_static_SearchUserDTO_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_SearchUserDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchUserDTO_descriptor,
        new java.lang.String[] { "Id", "UserName", });
    internal_static_CreateProjectDTO_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_CreateProjectDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateProjectDTO_descriptor,
        new java.lang.String[] { "UserId", "ProjectName", });
    internal_static_SearchProjectDTO_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_SearchProjectDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchProjectDTO_descriptor,
        new java.lang.String[] { "Userid", "UserName", "CompletedStatus", "ProjectName", });
    internal_static_UpdateProjectDTO_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_UpdateProjectDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateProjectDTO_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_CreateTaskDTO_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_CreateTaskDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateTaskDTO_descriptor,
        new java.lang.String[] { "ProjectId", "OwnerId", "Title", });
    internal_static_UpdateTaskDTO_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_UpdateTaskDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateTaskDTO_descriptor,
        new java.lang.String[] { "Id", "IsCompleted", });
    internal_static_SearchTaskDTO_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_SearchTaskDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchTaskDTO_descriptor,
        new java.lang.String[] { "UserId", "UserName", "ProjectId", "ProjectName", "Title", "IsCompleted", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
