// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SEP.proto

package com.sep.protobuf;

/**
 * Protobuf type {@code Task}
 */
public final class Task extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Task)
    TaskOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Task.newBuilder() to construct.
  private Task(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Task() {
    title_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Task();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Task(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            com.sep.protobuf.Project.Builder subBuilder = null;
            if (belongsTo_ != null) {
              subBuilder = belongsTo_.toBuilder();
            }
            belongsTo_ = input.readMessage(com.sep.protobuf.Project.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(belongsTo_);
              belongsTo_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            title_ = s;
            break;
          }
          case 34: {
            com.sep.protobuf.User.Builder subBuilder = null;
            if (owner_ != null) {
              subBuilder = owner_.toBuilder();
            }
            owner_ = input.readMessage(com.sep.protobuf.User.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(owner_);
              owner_ = subBuilder.buildPartial();
            }

            break;
          }
          case 40: {

            isCompleted_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sep.protobuf.SEP.internal_static_Task_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sep.protobuf.SEP.internal_static_Task_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sep.protobuf.Task.class, com.sep.protobuf.Task.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int BELONGSTO_FIELD_NUMBER = 2;
  private com.sep.protobuf.Project belongsTo_;
  /**
   * <code>.Project belongsTo = 2;</code>
   * @return Whether the belongsTo field is set.
   */
  @java.lang.Override
  public boolean hasBelongsTo() {
    return belongsTo_ != null;
  }
  /**
   * <code>.Project belongsTo = 2;</code>
   * @return The belongsTo.
   */
  @java.lang.Override
  public com.sep.protobuf.Project getBelongsTo() {
    return belongsTo_ == null ? com.sep.protobuf.Project.getDefaultInstance() : belongsTo_;
  }
  /**
   * <code>.Project belongsTo = 2;</code>
   */
  @java.lang.Override
  public com.sep.protobuf.ProjectOrBuilder getBelongsToOrBuilder() {
    return getBelongsTo();
  }

  public static final int TITLE_FIELD_NUMBER = 3;
  private volatile java.lang.Object title_;
  /**
   * <code>string title = 3;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 3;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OWNER_FIELD_NUMBER = 4;
  private com.sep.protobuf.User owner_;
  /**
   * <code>.User owner = 4;</code>
   * @return Whether the owner field is set.
   */
  @java.lang.Override
  public boolean hasOwner() {
    return owner_ != null;
  }
  /**
   * <code>.User owner = 4;</code>
   * @return The owner.
   */
  @java.lang.Override
  public com.sep.protobuf.User getOwner() {
    return owner_ == null ? com.sep.protobuf.User.getDefaultInstance() : owner_;
  }
  /**
   * <code>.User owner = 4;</code>
   */
  @java.lang.Override
  public com.sep.protobuf.UserOrBuilder getOwnerOrBuilder() {
    return getOwner();
  }

  public static final int ISCOMPLETED_FIELD_NUMBER = 5;
  private boolean isCompleted_;
  /**
   * <code>bool isCompleted = 5;</code>
   * @return The isCompleted.
   */
  @java.lang.Override
  public boolean getIsCompleted() {
    return isCompleted_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (belongsTo_ != null) {
      output.writeMessage(2, getBelongsTo());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, title_);
    }
    if (owner_ != null) {
      output.writeMessage(4, getOwner());
    }
    if (isCompleted_ != false) {
      output.writeBool(5, isCompleted_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (belongsTo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getBelongsTo());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, title_);
    }
    if (owner_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getOwner());
    }
    if (isCompleted_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, isCompleted_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sep.protobuf.Task)) {
      return super.equals(obj);
    }
    com.sep.protobuf.Task other = (com.sep.protobuf.Task) obj;

    if (getId()
        != other.getId()) return false;
    if (hasBelongsTo() != other.hasBelongsTo()) return false;
    if (hasBelongsTo()) {
      if (!getBelongsTo()
          .equals(other.getBelongsTo())) return false;
    }
    if (!getTitle()
        .equals(other.getTitle())) return false;
    if (hasOwner() != other.hasOwner()) return false;
    if (hasOwner()) {
      if (!getOwner()
          .equals(other.getOwner())) return false;
    }
    if (getIsCompleted()
        != other.getIsCompleted()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    if (hasBelongsTo()) {
      hash = (37 * hash) + BELONGSTO_FIELD_NUMBER;
      hash = (53 * hash) + getBelongsTo().hashCode();
    }
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    if (hasOwner()) {
      hash = (37 * hash) + OWNER_FIELD_NUMBER;
      hash = (53 * hash) + getOwner().hashCode();
    }
    hash = (37 * hash) + ISCOMPLETED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsCompleted());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sep.protobuf.Task parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sep.protobuf.Task parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sep.protobuf.Task parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sep.protobuf.Task parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sep.protobuf.Task parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sep.protobuf.Task parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sep.protobuf.Task parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sep.protobuf.Task parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sep.protobuf.Task parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.sep.protobuf.Task parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sep.protobuf.Task parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sep.protobuf.Task parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sep.protobuf.Task prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Task}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Task)
      com.sep.protobuf.TaskOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sep.protobuf.SEP.internal_static_Task_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sep.protobuf.SEP.internal_static_Task_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sep.protobuf.Task.class, com.sep.protobuf.Task.Builder.class);
    }

    // Construct using com.sep.protobuf.Task.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      if (belongsToBuilder_ == null) {
        belongsTo_ = null;
      } else {
        belongsTo_ = null;
        belongsToBuilder_ = null;
      }
      title_ = "";

      if (ownerBuilder_ == null) {
        owner_ = null;
      } else {
        owner_ = null;
        ownerBuilder_ = null;
      }
      isCompleted_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sep.protobuf.SEP.internal_static_Task_descriptor;
    }

    @java.lang.Override
    public com.sep.protobuf.Task getDefaultInstanceForType() {
      return com.sep.protobuf.Task.getDefaultInstance();
    }

    @java.lang.Override
    public com.sep.protobuf.Task build() {
      com.sep.protobuf.Task result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sep.protobuf.Task buildPartial() {
      com.sep.protobuf.Task result = new com.sep.protobuf.Task(this);
      result.id_ = id_;
      if (belongsToBuilder_ == null) {
        result.belongsTo_ = belongsTo_;
      } else {
        result.belongsTo_ = belongsToBuilder_.build();
      }
      result.title_ = title_;
      if (ownerBuilder_ == null) {
        result.owner_ = owner_;
      } else {
        result.owner_ = ownerBuilder_.build();
      }
      result.isCompleted_ = isCompleted_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sep.protobuf.Task) {
        return mergeFrom((com.sep.protobuf.Task)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sep.protobuf.Task other) {
      if (other == com.sep.protobuf.Task.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.hasBelongsTo()) {
        mergeBelongsTo(other.getBelongsTo());
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        onChanged();
      }
      if (other.hasOwner()) {
        mergeOwner(other.getOwner());
      }
      if (other.getIsCompleted() != false) {
        setIsCompleted(other.getIsCompleted());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.sep.protobuf.Task parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.sep.protobuf.Task) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private com.sep.protobuf.Project belongsTo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sep.protobuf.Project, com.sep.protobuf.Project.Builder, com.sep.protobuf.ProjectOrBuilder> belongsToBuilder_;
    /**
     * <code>.Project belongsTo = 2;</code>
     * @return Whether the belongsTo field is set.
     */
    public boolean hasBelongsTo() {
      return belongsToBuilder_ != null || belongsTo_ != null;
    }
    /**
     * <code>.Project belongsTo = 2;</code>
     * @return The belongsTo.
     */
    public com.sep.protobuf.Project getBelongsTo() {
      if (belongsToBuilder_ == null) {
        return belongsTo_ == null ? com.sep.protobuf.Project.getDefaultInstance() : belongsTo_;
      } else {
        return belongsToBuilder_.getMessage();
      }
    }
    /**
     * <code>.Project belongsTo = 2;</code>
     */
    public Builder setBelongsTo(com.sep.protobuf.Project value) {
      if (belongsToBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        belongsTo_ = value;
        onChanged();
      } else {
        belongsToBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Project belongsTo = 2;</code>
     */
    public Builder setBelongsTo(
        com.sep.protobuf.Project.Builder builderForValue) {
      if (belongsToBuilder_ == null) {
        belongsTo_ = builderForValue.build();
        onChanged();
      } else {
        belongsToBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Project belongsTo = 2;</code>
     */
    public Builder mergeBelongsTo(com.sep.protobuf.Project value) {
      if (belongsToBuilder_ == null) {
        if (belongsTo_ != null) {
          belongsTo_ =
            com.sep.protobuf.Project.newBuilder(belongsTo_).mergeFrom(value).buildPartial();
        } else {
          belongsTo_ = value;
        }
        onChanged();
      } else {
        belongsToBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Project belongsTo = 2;</code>
     */
    public Builder clearBelongsTo() {
      if (belongsToBuilder_ == null) {
        belongsTo_ = null;
        onChanged();
      } else {
        belongsTo_ = null;
        belongsToBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Project belongsTo = 2;</code>
     */
    public com.sep.protobuf.Project.Builder getBelongsToBuilder() {
      
      onChanged();
      return getBelongsToFieldBuilder().getBuilder();
    }
    /**
     * <code>.Project belongsTo = 2;</code>
     */
    public com.sep.protobuf.ProjectOrBuilder getBelongsToOrBuilder() {
      if (belongsToBuilder_ != null) {
        return belongsToBuilder_.getMessageOrBuilder();
      } else {
        return belongsTo_ == null ?
            com.sep.protobuf.Project.getDefaultInstance() : belongsTo_;
      }
    }
    /**
     * <code>.Project belongsTo = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sep.protobuf.Project, com.sep.protobuf.Project.Builder, com.sep.protobuf.ProjectOrBuilder> 
        getBelongsToFieldBuilder() {
      if (belongsToBuilder_ == null) {
        belongsToBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.sep.protobuf.Project, com.sep.protobuf.Project.Builder, com.sep.protobuf.ProjectOrBuilder>(
                getBelongsTo(),
                getParentForChildren(),
                isClean());
        belongsTo_ = null;
      }
      return belongsToBuilder_;
    }

    private java.lang.Object title_ = "";
    /**
     * <code>string title = 3;</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 3;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 3;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      title_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      
      title_ = getDefaultInstance().getTitle();
      onChanged();
      return this;
    }
    /**
     * <code>string title = 3;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      title_ = value;
      onChanged();
      return this;
    }

    private com.sep.protobuf.User owner_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sep.protobuf.User, com.sep.protobuf.User.Builder, com.sep.protobuf.UserOrBuilder> ownerBuilder_;
    /**
     * <code>.User owner = 4;</code>
     * @return Whether the owner field is set.
     */
    public boolean hasOwner() {
      return ownerBuilder_ != null || owner_ != null;
    }
    /**
     * <code>.User owner = 4;</code>
     * @return The owner.
     */
    public com.sep.protobuf.User getOwner() {
      if (ownerBuilder_ == null) {
        return owner_ == null ? com.sep.protobuf.User.getDefaultInstance() : owner_;
      } else {
        return ownerBuilder_.getMessage();
      }
    }
    /**
     * <code>.User owner = 4;</code>
     */
    public Builder setOwner(com.sep.protobuf.User value) {
      if (ownerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        owner_ = value;
        onChanged();
      } else {
        ownerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.User owner = 4;</code>
     */
    public Builder setOwner(
        com.sep.protobuf.User.Builder builderForValue) {
      if (ownerBuilder_ == null) {
        owner_ = builderForValue.build();
        onChanged();
      } else {
        ownerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.User owner = 4;</code>
     */
    public Builder mergeOwner(com.sep.protobuf.User value) {
      if (ownerBuilder_ == null) {
        if (owner_ != null) {
          owner_ =
            com.sep.protobuf.User.newBuilder(owner_).mergeFrom(value).buildPartial();
        } else {
          owner_ = value;
        }
        onChanged();
      } else {
        ownerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.User owner = 4;</code>
     */
    public Builder clearOwner() {
      if (ownerBuilder_ == null) {
        owner_ = null;
        onChanged();
      } else {
        owner_ = null;
        ownerBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.User owner = 4;</code>
     */
    public com.sep.protobuf.User.Builder getOwnerBuilder() {
      
      onChanged();
      return getOwnerFieldBuilder().getBuilder();
    }
    /**
     * <code>.User owner = 4;</code>
     */
    public com.sep.protobuf.UserOrBuilder getOwnerOrBuilder() {
      if (ownerBuilder_ != null) {
        return ownerBuilder_.getMessageOrBuilder();
      } else {
        return owner_ == null ?
            com.sep.protobuf.User.getDefaultInstance() : owner_;
      }
    }
    /**
     * <code>.User owner = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sep.protobuf.User, com.sep.protobuf.User.Builder, com.sep.protobuf.UserOrBuilder> 
        getOwnerFieldBuilder() {
      if (ownerBuilder_ == null) {
        ownerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.sep.protobuf.User, com.sep.protobuf.User.Builder, com.sep.protobuf.UserOrBuilder>(
                getOwner(),
                getParentForChildren(),
                isClean());
        owner_ = null;
      }
      return ownerBuilder_;
    }

    private boolean isCompleted_ ;
    /**
     * <code>bool isCompleted = 5;</code>
     * @return The isCompleted.
     */
    @java.lang.Override
    public boolean getIsCompleted() {
      return isCompleted_;
    }
    /**
     * <code>bool isCompleted = 5;</code>
     * @param value The isCompleted to set.
     * @return This builder for chaining.
     */
    public Builder setIsCompleted(boolean value) {
      
      isCompleted_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool isCompleted = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsCompleted() {
      
      isCompleted_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Task)
  }

  // @@protoc_insertion_point(class_scope:Task)
  private static final com.sep.protobuf.Task DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sep.protobuf.Task();
  }

  public static com.sep.protobuf.Task getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Task>
      PARSER = new com.google.protobuf.AbstractParser<Task>() {
    @java.lang.Override
    public Task parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Task(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Task> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Task> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sep.protobuf.Task getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

