// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SEP.proto

package com.sep.protobuf;

public interface UpdateTaskDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UpdateTaskDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>bool isCompleted = 2;</code>
   * @return The isCompleted.
   */
  boolean getIsCompleted();
}
