// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SEP.proto

package com.sep.protobuf;

/**
 * Protobuf type {@code User}
 */
public final class User extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:User)
    UserOrBuilder {
private static final long serialVersionUID = 0L;
  // Use User.newBuilder() to construct.
  private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private User() {
    userName_ = "";
    password_ = "";
    taskList_ = java.util.Collections.emptyList();
    projectList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new User();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private User(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            userName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            password_ = s;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              taskList_ = new java.util.ArrayList<com.sep.protobuf.Task>();
              mutable_bitField0_ |= 0x00000001;
            }
            taskList_.add(
                input.readMessage(com.sep.protobuf.Task.parser(), extensionRegistry));
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              projectList_ = new java.util.ArrayList<com.sep.protobuf.Project>();
              mutable_bitField0_ |= 0x00000002;
            }
            projectList_.add(
                input.readMessage(com.sep.protobuf.Project.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        taskList_ = java.util.Collections.unmodifiableList(taskList_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        projectList_ = java.util.Collections.unmodifiableList(projectList_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sep.protobuf.SEP.internal_static_User_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sep.protobuf.SEP.internal_static_User_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sep.protobuf.User.class, com.sep.protobuf.User.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int USERNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object userName_;
  /**
   * <code>string UserName = 2;</code>
   * @return The userName.
   */
  @java.lang.Override
  public java.lang.String getUserName() {
    java.lang.Object ref = userName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userName_ = s;
      return s;
    }
  }
  /**
   * <code>string UserName = 2;</code>
   * @return The bytes for userName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserNameBytes() {
    java.lang.Object ref = userName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PASSWORD_FIELD_NUMBER = 3;
  private volatile java.lang.Object password_;
  /**
   * <code>string Password = 3;</code>
   * @return The password.
   */
  @java.lang.Override
  public java.lang.String getPassword() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      password_ = s;
      return s;
    }
  }
  /**
   * <code>string Password = 3;</code>
   * @return The bytes for password.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      password_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TASKLIST_FIELD_NUMBER = 4;
  private java.util.List<com.sep.protobuf.Task> taskList_;
  /**
   * <code>repeated .Task taskList = 4;</code>
   */
  @java.lang.Override
  public java.util.List<com.sep.protobuf.Task> getTaskListList() {
    return taskList_;
  }
  /**
   * <code>repeated .Task taskList = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.sep.protobuf.TaskOrBuilder> 
      getTaskListOrBuilderList() {
    return taskList_;
  }
  /**
   * <code>repeated .Task taskList = 4;</code>
   */
  @java.lang.Override
  public int getTaskListCount() {
    return taskList_.size();
  }
  /**
   * <code>repeated .Task taskList = 4;</code>
   */
  @java.lang.Override
  public com.sep.protobuf.Task getTaskList(int index) {
    return taskList_.get(index);
  }
  /**
   * <code>repeated .Task taskList = 4;</code>
   */
  @java.lang.Override
  public com.sep.protobuf.TaskOrBuilder getTaskListOrBuilder(
      int index) {
    return taskList_.get(index);
  }

  public static final int PROJECTLIST_FIELD_NUMBER = 5;
  private java.util.List<com.sep.protobuf.Project> projectList_;
  /**
   * <code>repeated .Project projectList = 5;</code>
   */
  @java.lang.Override
  public java.util.List<com.sep.protobuf.Project> getProjectListList() {
    return projectList_;
  }
  /**
   * <code>repeated .Project projectList = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.sep.protobuf.ProjectOrBuilder> 
      getProjectListOrBuilderList() {
    return projectList_;
  }
  /**
   * <code>repeated .Project projectList = 5;</code>
   */
  @java.lang.Override
  public int getProjectListCount() {
    return projectList_.size();
  }
  /**
   * <code>repeated .Project projectList = 5;</code>
   */
  @java.lang.Override
  public com.sep.protobuf.Project getProjectList(int index) {
    return projectList_.get(index);
  }
  /**
   * <code>repeated .Project projectList = 5;</code>
   */
  @java.lang.Override
  public com.sep.protobuf.ProjectOrBuilder getProjectListOrBuilder(
      int index) {
    return projectList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, password_);
    }
    for (int i = 0; i < taskList_.size(); i++) {
      output.writeMessage(4, taskList_.get(i));
    }
    for (int i = 0; i < projectList_.size(); i++) {
      output.writeMessage(5, projectList_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, password_);
    }
    for (int i = 0; i < taskList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, taskList_.get(i));
    }
    for (int i = 0; i < projectList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, projectList_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sep.protobuf.User)) {
      return super.equals(obj);
    }
    com.sep.protobuf.User other = (com.sep.protobuf.User) obj;

    if (getId()
        != other.getId()) return false;
    if (!getUserName()
        .equals(other.getUserName())) return false;
    if (!getPassword()
        .equals(other.getPassword())) return false;
    if (!getTaskListList()
        .equals(other.getTaskListList())) return false;
    if (!getProjectListList()
        .equals(other.getProjectListList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUserName().hashCode();
    hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
    hash = (53 * hash) + getPassword().hashCode();
    if (getTaskListCount() > 0) {
      hash = (37 * hash) + TASKLIST_FIELD_NUMBER;
      hash = (53 * hash) + getTaskListList().hashCode();
    }
    if (getProjectListCount() > 0) {
      hash = (37 * hash) + PROJECTLIST_FIELD_NUMBER;
      hash = (53 * hash) + getProjectListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sep.protobuf.User parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sep.protobuf.User parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sep.protobuf.User parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sep.protobuf.User parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sep.protobuf.User parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sep.protobuf.User parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sep.protobuf.User parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sep.protobuf.User parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sep.protobuf.User parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.sep.protobuf.User parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sep.protobuf.User parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sep.protobuf.User parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sep.protobuf.User prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code User}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:User)
      com.sep.protobuf.UserOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sep.protobuf.SEP.internal_static_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sep.protobuf.SEP.internal_static_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sep.protobuf.User.class, com.sep.protobuf.User.Builder.class);
    }

    // Construct using com.sep.protobuf.User.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTaskListFieldBuilder();
        getProjectListFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      userName_ = "";

      password_ = "";

      if (taskListBuilder_ == null) {
        taskList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        taskListBuilder_.clear();
      }
      if (projectListBuilder_ == null) {
        projectList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        projectListBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sep.protobuf.SEP.internal_static_User_descriptor;
    }

    @java.lang.Override
    public com.sep.protobuf.User getDefaultInstanceForType() {
      return com.sep.protobuf.User.getDefaultInstance();
    }

    @java.lang.Override
    public com.sep.protobuf.User build() {
      com.sep.protobuf.User result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sep.protobuf.User buildPartial() {
      com.sep.protobuf.User result = new com.sep.protobuf.User(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.userName_ = userName_;
      result.password_ = password_;
      if (taskListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          taskList_ = java.util.Collections.unmodifiableList(taskList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.taskList_ = taskList_;
      } else {
        result.taskList_ = taskListBuilder_.build();
      }
      if (projectListBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          projectList_ = java.util.Collections.unmodifiableList(projectList_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.projectList_ = projectList_;
      } else {
        result.projectList_ = projectListBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sep.protobuf.User) {
        return mergeFrom((com.sep.protobuf.User)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sep.protobuf.User other) {
      if (other == com.sep.protobuf.User.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getUserName().isEmpty()) {
        userName_ = other.userName_;
        onChanged();
      }
      if (!other.getPassword().isEmpty()) {
        password_ = other.password_;
        onChanged();
      }
      if (taskListBuilder_ == null) {
        if (!other.taskList_.isEmpty()) {
          if (taskList_.isEmpty()) {
            taskList_ = other.taskList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTaskListIsMutable();
            taskList_.addAll(other.taskList_);
          }
          onChanged();
        }
      } else {
        if (!other.taskList_.isEmpty()) {
          if (taskListBuilder_.isEmpty()) {
            taskListBuilder_.dispose();
            taskListBuilder_ = null;
            taskList_ = other.taskList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            taskListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTaskListFieldBuilder() : null;
          } else {
            taskListBuilder_.addAllMessages(other.taskList_);
          }
        }
      }
      if (projectListBuilder_ == null) {
        if (!other.projectList_.isEmpty()) {
          if (projectList_.isEmpty()) {
            projectList_ = other.projectList_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureProjectListIsMutable();
            projectList_.addAll(other.projectList_);
          }
          onChanged();
        }
      } else {
        if (!other.projectList_.isEmpty()) {
          if (projectListBuilder_.isEmpty()) {
            projectListBuilder_.dispose();
            projectListBuilder_ = null;
            projectList_ = other.projectList_;
            bitField0_ = (bitField0_ & ~0x00000002);
            projectListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getProjectListFieldBuilder() : null;
          } else {
            projectListBuilder_.addAllMessages(other.projectList_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.sep.protobuf.User parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.sep.protobuf.User) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object userName_ = "";
    /**
     * <code>string UserName = 2;</code>
     * @return The userName.
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string UserName = 2;</code>
     * @return The bytes for userName.
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string UserName = 2;</code>
     * @param value The userName to set.
     * @return This builder for chaining.
     */
    public Builder setUserName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string UserName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserName() {
      
      userName_ = getDefaultInstance().getUserName();
      onChanged();
      return this;
    }
    /**
     * <code>string UserName = 2;</code>
     * @param value The bytes for userName to set.
     * @return This builder for chaining.
     */
    public Builder setUserNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object password_ = "";
    /**
     * <code>string Password = 3;</code>
     * @return The password.
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Password = 3;</code>
     * @return The bytes for password.
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Password = 3;</code>
     * @param value The password to set.
     * @return This builder for chaining.
     */
    public Builder setPassword(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      password_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Password = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPassword() {
      
      password_ = getDefaultInstance().getPassword();
      onChanged();
      return this;
    }
    /**
     * <code>string Password = 3;</code>
     * @param value The bytes for password to set.
     * @return This builder for chaining.
     */
    public Builder setPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      password_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.sep.protobuf.Task> taskList_ =
      java.util.Collections.emptyList();
    private void ensureTaskListIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        taskList_ = new java.util.ArrayList<com.sep.protobuf.Task>(taskList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.sep.protobuf.Task, com.sep.protobuf.Task.Builder, com.sep.protobuf.TaskOrBuilder> taskListBuilder_;

    /**
     * <code>repeated .Task taskList = 4;</code>
     */
    public java.util.List<com.sep.protobuf.Task> getTaskListList() {
      if (taskListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(taskList_);
      } else {
        return taskListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Task taskList = 4;</code>
     */
    public int getTaskListCount() {
      if (taskListBuilder_ == null) {
        return taskList_.size();
      } else {
        return taskListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Task taskList = 4;</code>
     */
    public com.sep.protobuf.Task getTaskList(int index) {
      if (taskListBuilder_ == null) {
        return taskList_.get(index);
      } else {
        return taskListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Task taskList = 4;</code>
     */
    public Builder setTaskList(
        int index, com.sep.protobuf.Task value) {
      if (taskListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTaskListIsMutable();
        taskList_.set(index, value);
        onChanged();
      } else {
        taskListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Task taskList = 4;</code>
     */
    public Builder setTaskList(
        int index, com.sep.protobuf.Task.Builder builderForValue) {
      if (taskListBuilder_ == null) {
        ensureTaskListIsMutable();
        taskList_.set(index, builderForValue.build());
        onChanged();
      } else {
        taskListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Task taskList = 4;</code>
     */
    public Builder addTaskList(com.sep.protobuf.Task value) {
      if (taskListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTaskListIsMutable();
        taskList_.add(value);
        onChanged();
      } else {
        taskListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Task taskList = 4;</code>
     */
    public Builder addTaskList(
        int index, com.sep.protobuf.Task value) {
      if (taskListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTaskListIsMutable();
        taskList_.add(index, value);
        onChanged();
      } else {
        taskListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Task taskList = 4;</code>
     */
    public Builder addTaskList(
        com.sep.protobuf.Task.Builder builderForValue) {
      if (taskListBuilder_ == null) {
        ensureTaskListIsMutable();
        taskList_.add(builderForValue.build());
        onChanged();
      } else {
        taskListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Task taskList = 4;</code>
     */
    public Builder addTaskList(
        int index, com.sep.protobuf.Task.Builder builderForValue) {
      if (taskListBuilder_ == null) {
        ensureTaskListIsMutable();
        taskList_.add(index, builderForValue.build());
        onChanged();
      } else {
        taskListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Task taskList = 4;</code>
     */
    public Builder addAllTaskList(
        java.lang.Iterable<? extends com.sep.protobuf.Task> values) {
      if (taskListBuilder_ == null) {
        ensureTaskListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, taskList_);
        onChanged();
      } else {
        taskListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Task taskList = 4;</code>
     */
    public Builder clearTaskList() {
      if (taskListBuilder_ == null) {
        taskList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        taskListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Task taskList = 4;</code>
     */
    public Builder removeTaskList(int index) {
      if (taskListBuilder_ == null) {
        ensureTaskListIsMutable();
        taskList_.remove(index);
        onChanged();
      } else {
        taskListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Task taskList = 4;</code>
     */
    public com.sep.protobuf.Task.Builder getTaskListBuilder(
        int index) {
      return getTaskListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Task taskList = 4;</code>
     */
    public com.sep.protobuf.TaskOrBuilder getTaskListOrBuilder(
        int index) {
      if (taskListBuilder_ == null) {
        return taskList_.get(index);  } else {
        return taskListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Task taskList = 4;</code>
     */
    public java.util.List<? extends com.sep.protobuf.TaskOrBuilder> 
         getTaskListOrBuilderList() {
      if (taskListBuilder_ != null) {
        return taskListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(taskList_);
      }
    }
    /**
     * <code>repeated .Task taskList = 4;</code>
     */
    public com.sep.protobuf.Task.Builder addTaskListBuilder() {
      return getTaskListFieldBuilder().addBuilder(
          com.sep.protobuf.Task.getDefaultInstance());
    }
    /**
     * <code>repeated .Task taskList = 4;</code>
     */
    public com.sep.protobuf.Task.Builder addTaskListBuilder(
        int index) {
      return getTaskListFieldBuilder().addBuilder(
          index, com.sep.protobuf.Task.getDefaultInstance());
    }
    /**
     * <code>repeated .Task taskList = 4;</code>
     */
    public java.util.List<com.sep.protobuf.Task.Builder> 
         getTaskListBuilderList() {
      return getTaskListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.sep.protobuf.Task, com.sep.protobuf.Task.Builder, com.sep.protobuf.TaskOrBuilder> 
        getTaskListFieldBuilder() {
      if (taskListBuilder_ == null) {
        taskListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.sep.protobuf.Task, com.sep.protobuf.Task.Builder, com.sep.protobuf.TaskOrBuilder>(
                taskList_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        taskList_ = null;
      }
      return taskListBuilder_;
    }

    private java.util.List<com.sep.protobuf.Project> projectList_ =
      java.util.Collections.emptyList();
    private void ensureProjectListIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        projectList_ = new java.util.ArrayList<com.sep.protobuf.Project>(projectList_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.sep.protobuf.Project, com.sep.protobuf.Project.Builder, com.sep.protobuf.ProjectOrBuilder> projectListBuilder_;

    /**
     * <code>repeated .Project projectList = 5;</code>
     */
    public java.util.List<com.sep.protobuf.Project> getProjectListList() {
      if (projectListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(projectList_);
      } else {
        return projectListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Project projectList = 5;</code>
     */
    public int getProjectListCount() {
      if (projectListBuilder_ == null) {
        return projectList_.size();
      } else {
        return projectListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Project projectList = 5;</code>
     */
    public com.sep.protobuf.Project getProjectList(int index) {
      if (projectListBuilder_ == null) {
        return projectList_.get(index);
      } else {
        return projectListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Project projectList = 5;</code>
     */
    public Builder setProjectList(
        int index, com.sep.protobuf.Project value) {
      if (projectListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProjectListIsMutable();
        projectList_.set(index, value);
        onChanged();
      } else {
        projectListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Project projectList = 5;</code>
     */
    public Builder setProjectList(
        int index, com.sep.protobuf.Project.Builder builderForValue) {
      if (projectListBuilder_ == null) {
        ensureProjectListIsMutable();
        projectList_.set(index, builderForValue.build());
        onChanged();
      } else {
        projectListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Project projectList = 5;</code>
     */
    public Builder addProjectList(com.sep.protobuf.Project value) {
      if (projectListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProjectListIsMutable();
        projectList_.add(value);
        onChanged();
      } else {
        projectListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Project projectList = 5;</code>
     */
    public Builder addProjectList(
        int index, com.sep.protobuf.Project value) {
      if (projectListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProjectListIsMutable();
        projectList_.add(index, value);
        onChanged();
      } else {
        projectListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Project projectList = 5;</code>
     */
    public Builder addProjectList(
        com.sep.protobuf.Project.Builder builderForValue) {
      if (projectListBuilder_ == null) {
        ensureProjectListIsMutable();
        projectList_.add(builderForValue.build());
        onChanged();
      } else {
        projectListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Project projectList = 5;</code>
     */
    public Builder addProjectList(
        int index, com.sep.protobuf.Project.Builder builderForValue) {
      if (projectListBuilder_ == null) {
        ensureProjectListIsMutable();
        projectList_.add(index, builderForValue.build());
        onChanged();
      } else {
        projectListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Project projectList = 5;</code>
     */
    public Builder addAllProjectList(
        java.lang.Iterable<? extends com.sep.protobuf.Project> values) {
      if (projectListBuilder_ == null) {
        ensureProjectListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, projectList_);
        onChanged();
      } else {
        projectListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Project projectList = 5;</code>
     */
    public Builder clearProjectList() {
      if (projectListBuilder_ == null) {
        projectList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        projectListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Project projectList = 5;</code>
     */
    public Builder removeProjectList(int index) {
      if (projectListBuilder_ == null) {
        ensureProjectListIsMutable();
        projectList_.remove(index);
        onChanged();
      } else {
        projectListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Project projectList = 5;</code>
     */
    public com.sep.protobuf.Project.Builder getProjectListBuilder(
        int index) {
      return getProjectListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Project projectList = 5;</code>
     */
    public com.sep.protobuf.ProjectOrBuilder getProjectListOrBuilder(
        int index) {
      if (projectListBuilder_ == null) {
        return projectList_.get(index);  } else {
        return projectListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Project projectList = 5;</code>
     */
    public java.util.List<? extends com.sep.protobuf.ProjectOrBuilder> 
         getProjectListOrBuilderList() {
      if (projectListBuilder_ != null) {
        return projectListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(projectList_);
      }
    }
    /**
     * <code>repeated .Project projectList = 5;</code>
     */
    public com.sep.protobuf.Project.Builder addProjectListBuilder() {
      return getProjectListFieldBuilder().addBuilder(
          com.sep.protobuf.Project.getDefaultInstance());
    }
    /**
     * <code>repeated .Project projectList = 5;</code>
     */
    public com.sep.protobuf.Project.Builder addProjectListBuilder(
        int index) {
      return getProjectListFieldBuilder().addBuilder(
          index, com.sep.protobuf.Project.getDefaultInstance());
    }
    /**
     * <code>repeated .Project projectList = 5;</code>
     */
    public java.util.List<com.sep.protobuf.Project.Builder> 
         getProjectListBuilderList() {
      return getProjectListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.sep.protobuf.Project, com.sep.protobuf.Project.Builder, com.sep.protobuf.ProjectOrBuilder> 
        getProjectListFieldBuilder() {
      if (projectListBuilder_ == null) {
        projectListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.sep.protobuf.Project, com.sep.protobuf.Project.Builder, com.sep.protobuf.ProjectOrBuilder>(
                projectList_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        projectList_ = null;
      }
      return projectListBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:User)
  }

  // @@protoc_insertion_point(class_scope:User)
  private static final com.sep.protobuf.User DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sep.protobuf.User();
  }

  public static com.sep.protobuf.User getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<User>
      PARSER = new com.google.protobuf.AbstractParser<User>() {
    @java.lang.Override
    public User parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new User(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<User> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<User> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sep.protobuf.User getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

