// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SEP.proto

package com.sep.protobuf;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string UserName = 2;</code>
   * @return The userName.
   */
  java.lang.String getUserName();
  /**
   * <code>string UserName = 2;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string Password = 3;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string Password = 3;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>repeated .Task taskList = 4;</code>
   */
  java.util.List<com.sep.protobuf.Task> 
      getTaskListList();
  /**
   * <code>repeated .Task taskList = 4;</code>
   */
  com.sep.protobuf.Task getTaskList(int index);
  /**
   * <code>repeated .Task taskList = 4;</code>
   */
  int getTaskListCount();
  /**
   * <code>repeated .Task taskList = 4;</code>
   */
  java.util.List<? extends com.sep.protobuf.TaskOrBuilder> 
      getTaskListOrBuilderList();
  /**
   * <code>repeated .Task taskList = 4;</code>
   */
  com.sep.protobuf.TaskOrBuilder getTaskListOrBuilder(
      int index);

  /**
   * <code>repeated .Project projectList = 5;</code>
   */
  java.util.List<com.sep.protobuf.Project> 
      getProjectListList();
  /**
   * <code>repeated .Project projectList = 5;</code>
   */
  com.sep.protobuf.Project getProjectList(int index);
  /**
   * <code>repeated .Project projectList = 5;</code>
   */
  int getProjectListCount();
  /**
   * <code>repeated .Project projectList = 5;</code>
   */
  java.util.List<? extends com.sep.protobuf.ProjectOrBuilder> 
      getProjectListOrBuilderList();
  /**
   * <code>repeated .Project projectList = 5;</code>
   */
  com.sep.protobuf.ProjectOrBuilder getProjectListOrBuilder(
      int index);
}
